Login/Controllers/RoleController.cs
using Login.Areas.Identity.Data;
using Login.Data;
using Login.Models.ApplicationUser;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;


namespace Login.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<LoginUser> _userManager;
        private readonly IApplicationUsers _userService;
        public RoleController(RoleManager<IdentityRole> roleManager,
            IApplicationUsers userService,
            UserManager<LoginUser> userManager)
        {
            _roleManager = roleManager;
            _userService = userService;
            _userManager = userManager;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var roles = _roleManager.Roles.ToList();
            var adminCheck = await _roleManager.RoleExistsAsync("Admin");
            var modCheck = await _roleManager.RoleExistsAsync("Mod");
            if (!adminCheck && !modCheck)
            {
                await _roleManager.CreateAsync(new IdentityRole("Admin"));
                await _roleManager.CreateAsync(new IdentityRole("Mod"));
            }

            return View(roles);
        }

        public IActionResult CreateRole()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateRole(IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    return NotFound();
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index");
        }

        public IActionResult AssignUser()
        {
            var userModel = _userService.GetAll().Select(user => new ProfileModel
            {
                UserId = user.Id,
                Username = user.UserName,
                UserRating = user.Ratting,
                Warnings = user.AccountWarnings
            })
                .ToList();

            var userList = new ProfileModelList { ProfileList = userModel };

            return View(userList);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> MakeAdmin()
        {
            await _userManager.AddToRoleAsync(await _userManager.GetUserAsync(User), "Admin");
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> MakeMod(string userId)
        {
            //unasign from others roles and then asign to new role
            LoginUser user = _userService.GetById(userId);

            var userRole = await _userManager.GetRolesAsync(user);
            foreach (var role in userRole)
            {
                //toggle
                if (role == "Mod")
                {
                    await _userManager.RemoveFromRoleAsync(user, "Mod");
                    return RedirectToAction("Index");
                }
            }

            await _userManager.AddToRoleAsync(user, "Mod");
            return RedirectToAction("Index");
        }

    }
}

Login/Controllers/SearchController.cs
using Login.Areas.Identity.Data;
using Login.Data;
using Login.Models;
using Login.Models.ApplicationUser;
using Login.Models.Search;
using Login.Models.Threadl;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace Login.Controllers
{
    public class SearchController : Controller
    {
        private readonly UserManager<LoginUser> _userManager;
        private readonly IChannel _channelService;
        private readonly IThread _threadService;
        private readonly IAlbum _albumService;
        private readonly IApplicationUsers _userService;

        public SearchController(UserManager<LoginUser> userManager, IChannel channelService, IThread threadService, IApplicationUsers userService, IAlbum albumService)
        {
            _userManager = userManager;
            _channelService = channelService;
            _threadService = threadService;
            _userService = userService;
            _albumService = albumService;
        }
        [ValidateAntiForgeryToken]
        public IActionResult Index(string searchInput, string searchArea, string searchOptions, string sortingOptions)
        {
            var searchResult = new SearchModel
            {
                ThreadsIncluded = false,
                ChannelsIncluded = false,
                UsersIncluded = false
            };
            var keywords = GetSearchKeywords(searchInput);  //Returns a list of search keywords
            if (searchArea.Equals("All") || searchArea.Equals("Threads"))
            {
                searchResult.ThreadsIncluded = true;
                searchResult.Threads = GetThreads(keywords, searchOptions, sortingOptions);
            }
            if (searchArea.Equals("All") || searchArea.Equals("Channels"))
            {
                searchResult.ChannelsIncluded = true;
                searchResult.Channels = GetChannels(keywords, searchOptions, sortingOptions);
            }
            if (searchArea.Equals("All") || searchArea.Equals("Users"))
            {
                searchResult.UsersIncluded = true;
                searchResult.Users = GetUsers(keywords, searchOptions, sortingOptions);
            }
            return View(searchResult);
        }
        private List<string> GetSearchKeywords(string searchInput)
        {
            List<string> keywords = new List<string>();
            string keyword = "";
            if (searchInput == null) return keywords;  //If input is null, then return an empty list
            while (searchInput.Length != 0)  //Loops through the entire input
            {
                if (searchInput.ElementAt(0).Equals((char)32) || searchInput.ElementAt(0).Equals((char)44)) //ASCII for whitespace and coma
                {
                    if (keyword.Length > 1)
                    {
                        keywords.Add(keyword); //Adds a keyword to the list if it is 2 or more characters long
                    }
                    keyword = ""; //reset the current keyword
                    searchInput = searchInput.Substring(1); //remove the first input character
                }
                else
                {
                    keyword += (searchInput.ElementAt(0)); //adds a character to the current keyword if it is not whitespace or coma
                    if (searchInput.Length == 1 && keyword.Length > 1)
                    {
                        keywords.Add(keyword); //Adds a keyword to the list if it is 2 or more characters long
                    }
                    searchInput = searchInput.Substring(1); //remove the first input character
                }
            }
            return keywords;
        }
        //Returns true if originalString either contains or equal to the keyword
        private bool StringContains(string originalString, string keyword)
        {
            if (originalString == null) return false;
            return originalString.IndexOf(keyword, StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private IEnumerable<ThreadModel> GetThreads(List<string> keywords, string searchOptions, string sortingOptions)
        {
            var threads = _threadService.GetAll().Where(thread => thread.AlbumId == 1).Where(thread => thread.Flagged == false);
            if (searchOptions.Equals("Keywords"))
            {
                foreach (var keyword in keywords) //Performs one step lookup further into the search. If the next keyword lookup produces an empty result, then skip it
                {
                    var oneStepLookup = threads.Where(thread => StringContains(thread.Title, keyword) || StringContains(thread.Description, keyword));
                    if (oneStepLookup.FirstOrDefault() != null) threads = oneStepLookup;
                }
            }
            else if (searchOptions.Equals("Tags"))
            {
                var tags = _channelService.GetAllTags();
                foreach (var keyword in keywords)
                {
                    var oneStepLookup = tags
                        .Where(tag => StringContains(tag.Name, keyword))
                        .Where(tag => tag.ThreadId != 0);
                    if (oneStepLookup.FirstOrDefault() != null) tags = oneStepLookup;
                }
                if (tags.Select(tag => _threadService.GetById(tag.ThreadId)).FirstOrDefault() != null) threads = tags.Select(tag => _threadService.GetById(tag.ThreadId)).Distinct();
            }
            if (sortingOptions.Equals("Votes"))
            {
                threads = threads.OrderByDescending(thread => thread.Votes);
            }
            else
            {
                threads = threads.OrderByDescending(thread => thread.CreateDate);
            }
            return threads.Select(thread => new ThreadModel
            {
                Id = thread.ID,
                Title = thread.Title,
                Rating = thread.Votes,
                Description = thread.Description,
                Picture = thread.Image,
                Created = thread.CreateDate
            });
        }
        private IEnumerable<ChannelModel> GetChannels(IEnumerable<string> keywords, string searchOptions, string sortingOptions)
        {
            var channels = _channelService.GetAll();
            if (searchOptions.Equals("Keywords"))
            {
                foreach (var keyword in keywords) //Performs one step lookup further into the search. If the next keyword lookup produces an empty result, then skip it
                {
                    var oneStepLookup = channels.Where(channel => StringContains(channel.Title, keyword) || StringContains(channel.Description, keyword));
                    if (oneStepLookup.FirstOrDefault() != null) channels = oneStepLookup;
                }
            }
            else if (searchOptions.Equals("Tags"))
            {
                var tags = _channelService.GetAllTags();
                foreach (var keyword in keywords)
                {
                    var oneStepLookup = tags
                        .Where(tag => StringContains(tag.Name, keyword))
                        .Where(tag => tag.ChannelId != 0);
                    if (oneStepLookup.FirstOrDefault() != null) tags = oneStepLookup;
                }
                if (tags.Select(tag => _channelService.GetChannel(tag.ChannelId).Result).FirstOrDefault() != null) channels = tags.Select(tag => _channelService.GetChannel(tag.ChannelId).Result).Distinct();
            }
            if (sortingOptions.Equals("Votes"))
            {
                channels.OrderByDescending(channel => GetChannelRating(channel));
            }
            else
            {
                channels = channels.OrderByDescending(channel => channel.CreationDate);
            }
            return channels.Select(channel => new ChannelModel
            {
                Title = channel.Title,
                ChannelRating = 0,
                Description = channel.Description,
                CreationDate = channel.CreationDate
            });
        }
        private int GetChannelRating(Channel channel)
        {
            var rating = _threadService.GetAll()
                    .Where(thread => thread.Album.Channel == channel)
                    .Where(thread => thread.AlbumId != 1)
                    .Sum(thread => thread.Votes);
            return rating;
        }
        private IEnumerable<ProfileModel> GetUsers(IEnumerable<string> keywords, string searchOptions, string sortingOptions)
        {
            var users = _userService.GetAll();
            foreach (var keyword in keywords) //Performs one step lookup further into the search. If the next keyword lookup produces an empty result, then skip it
            {
                var oneStepLookup = users.Where(user => StringContains(user.UserName, keyword));
                if (oneStepLookup.FirstOrDefault() != null) users = oneStepLookup;
            }
            if (sortingOptions.Equals("Votes"))
            {
                users = users.OrderByDescending(users => users.Ratting);
            }
            else
            {
                users = users.OrderByDescending(user => user.MemberSince);
            }
            return users.Select(user => new ProfileModel
            {
                Username = user.UserName,
                ProfileImageUrl = user.ProfileImageUrl,
                UserRating = user.Ratting,
                MemmberSince = user.MemberSince

            });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Login/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Login.Areas.Identity.Data

@inject SignInManager<LoginUser> SignInManager
@inject UserManager<LoginUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <div class="navbar navbar-expand navbar-fixed-top border-bottom border-success">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h1>Camaio</h1></a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item d-none d-lg-block">
                    <a class="nav-link" asp-area="" asp-controller="Channel" asp-action="Index">Channels</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <form class="dropdown dropleft"asp-area="" asp-controller="Search" asp-action="Index">
                        <button class="overflow-hidden btn mt-1 pt-1 mr-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Search
                        </button>
                        <div class="dropdown-menu bg-success mr-2" aria-labelledby="dropdownMenuButton">
                            <div class="input-group btn-group d-flex flex-row">
                                <div class="form-outline">
                                    <input type="search" name="searchInput" placeholder="Search" maxlength="128" id="form1" class="form-control rounded p-2 mx-2" onkeyup="searchFunc();"/>
                                </div>
                            </div>
                        </div>
                        <input name="searchArea" value="All" type="hidden">
                        <input name="searchOptions" value="Keywords" type="hidden">
                        <input name="sortingOptions" value="Votes" type="hidden">
                    </form>

                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Thread" asp-action="Create" asp-route-albumId=1>
                        Upload
                    </a>
                </li>
            </ul>
            <div class="dropdown nav-item dropleft">
                <button class="imagebutton overflow-hidden mx-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="h-100 w-100" src="~/pictures/avatar.png">
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <p class="mx-3">@UserManager.GetUserName(User)</p>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" id="manage" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-username="@UserManager.GetUserName(User)">Profile</a>
                    <a class="dropdown-item" id="manage" asp-area="" asp-controller="Profile" asp-action="Scores">Top Users</a>
                    <a class="dropdown-item" id="manage" asp-area="" asp-controller="Score" asp-action="Threads">Top Posts</a>
                    <a class="dropdown-item" id="manage" asp-controller="Achievement" asp-action="Index" asp-route-username="@UserManager.GetUserName(User)">Achievements</a>
                    <a class="dropdown-item" id="manage" asp-area="" asp-controller="Profile" asp-action="Followers" asp-route-username="@UserManager.GetUserName(User)">Following</a>
                    @if (User.IsInRole("Admin"))
                    {
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" id="manage" asp-area="" asp-controller="Achievement" asp-action="Create">Create Achievement</a>
                        <a class="dropdown-item" id="manage" asp-area="" asp-controller="Thread" asp-action="Reported">Reported Posts</a>
                        <a class="dropdown-item" id="manage" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                    }
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" id="manage" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Settings</a>
                    <form id="logoutForm" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button id="logout" type="submit" class="dropdown-item">Log out</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}
else
{  
    <div class="navbar navbar-expand navbar-fixed-top border-bottom border-success">
        <a class="navbar-brand mr-auto" asp-area="" asp-controller="Home" asp-action="Index"><h1>Camaio</h1></a>
        <ul class="navbar-nav">
            @if (!ViewData["Title"].Equals("Register"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Register</a>
                </li>
            }
            @if (!ViewData["Title"].Equals("Log In"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">Login</a>
                </li>
            }
        </ul>
    </div>
}

Login/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Login.Areas.Identity.Data
@inject SignInManager<LoginUser> SignInManager
@inject UserManager<LoginUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Camaio - A university driven project made by students providing a social media platform without any human in the pictures. " />
    <title>@ViewData["Title"] Camaio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/x-icon" href="~/pictures/logo.png">
</head>
<body>
  
	<header>
        <partial name="_HeaderPartial" />
	</header>

    @RenderBody()

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Camaio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>