Login/Models/Thread.cs
using System;
using System.Collections.Generic;

namespace Login.Models
{
    public class Thread
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public DateTime CreateDate { get; set; }
        public int Votes { get; set; }
        public int NoReports { get; set; }
        public bool Flagged { get; set; }
        public int AlbumId { get; set; }
        public Album Album { get; set; }

        //cords from the image
        public double? Lat { get; set; }
        public double? Lng { get; set; }

        public IEnumerable<Likes> LikedBy { get; set; }

        public IEnumerable<Report> Reports { get; set; }
        public IEnumerable<Tag> Tags { get; set; }
        public IEnumerable<Notification> Notifications { get; set; }
    }
}

Login/Models/UsersThreads/ThreadList.cs
using System.Collections.Generic;

namespace Login.Models.Threadl
{
    public class ThreadList
    {
        public IEnumerable<ThreadModel> ThreadLists { get; set; }
    }
}

Login/Controllers/MapController.cs
using Login.Areas.Identity.Data;
using Login.Data;
using Login.Models.Map;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Login.Controllers
{
    public class MapController : Controller
    {
        private readonly string apiUrl = "https://www.google.com/maps/embed/v1/place?q=";
        private readonly string apiKey = "&key=AIzaSyBtN6zSCAPIyvKcVHC_NL3mvkq5w9zixqg";

        private readonly IThread _threadService;
        private readonly IApplicationUsers _userService;
        public MapController(IThread threadService, IApplicationUsers userService)
        {
            _threadService = threadService;
            _userService = userService;
        }

        //there is a issue that it needs a 20, in the url for some reason i dont know why
        [Authorize]
        [Route("/Thread/Map/{threadId}")]
        public ActionResult Index(int threadId)
        {
            var thread = _threadService.GetById(threadId);

            if (thread.Lat == null || thread.Lng == null)
            {
                return RedirectToAction("Index", "Thread", new { id = threadId });
            }

            var model = new MapModel
            {
                Lat = thread.Lat,
                Lng = thread.Lng,
                Url = apiUrl + thread.Lat + "N%20" + thread.Lng + "W" + apiKey
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [Route("Profile/{userName}/Map/")]
        public ActionResult UsersThreadsListMap(string userName)
        {
            LoginUser user = _userService.GetByUserName(userName);
            if (user == null) NotFound();
            var listOfCords = UsersPostsLocation(userName);
            var model = new MapModelList { Username = userName, MapCordsList = listOfCords };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [Route("/map/api/{username}")]
        public JsonResult DataTest(string userName)
        {
            LoginUser user = _userService.GetByUserName(userName);
            if (user == null) NotFound();
            var listOfCords = UsersPostsLocation(userName);
            if (listOfCords.Count() == 0)
            {
                return Json(null);
            }
            var model = new MapModelList { Username = userName, MapCordsList = listOfCords };

            return Json(model);
        }

        private IEnumerable<MapModel> UsersPostsLocation(string userName)
        {
            return _threadService.UserThreadsWithoutAlbum(userName).Select(thread => new MapModel
            {
                Lat = thread.Lat,
                Lng = thread.Lng

            })
                .Where(x => x.Lat != null);
        }

    }
}

Login/Controllers/ThreadController.cs
using Login.Areas.Identity.Data;
using Login.Data;
using Login.Data.Interfaces;
using Login.Models;
using Login.Models.Threadl;
using Login.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;


namespace Login.Controllers
{
    public class ThreadController : Controller
    {
        //azure vision api key and endpoint
        static readonly string subscriptionKey = "5d7d56109a794e2b9532bdde2185755d";
        static readonly string endpoint = "https://camaioai.cognitiveservices.azure.com/";

        //injections
        private readonly IThread _service;
        private readonly IConfiguration _configuration;
        private readonly UserManager<LoginUser> _userManager;
        private readonly IUpload _uploadService;
        private readonly IChannel _channelService;
        private readonly IAlbum _albumService;
        private readonly IApplicationUsers _userService;
        private readonly IVision _visionService;


        public ThreadController(IThread thread,
            IConfiguration configuration,
            UserManager<LoginUser> userManager,
            IUpload uploadService,
            IApplicationUsers userService,
            IVision visionService,
            IAlbum albumService,
            IChannel channelService)
        {
            _service = thread;
            _configuration = configuration;
            _userManager = userManager;
            _uploadService = uploadService;
            _userService = userService;
            _visionService = visionService;
            _albumService = albumService;
            _channelService = channelService;

        }

        [Route("Thread/{id?}")]
        //To view ONE thread
        public IActionResult Index(int? id)
        {
            //get the id of the thread
            var thread = _service.GetById(id);
            if (thread == null) return NotFound(); //if the thread number does not exist then not found
            //make a list of users that liked the thread
            var listOfLikes = _service.ListOfLikes(id);
            //get the list of reports
            var numberOfReports = _service.ListOfReports(id).Count();
            var tags = _service.GetThreadTags(thread);

            //make a view model for the thread
            var model = new ThreadModel
            {
                Id = thread.ID,
                AuthorId = thread.UserID,
                AuthorUserName = thread.UserName,
                Created = thread.CreateDate,
                Description = thread.Description,
                Picture = thread.Image,
                Title = thread.Title,
                Rating = listOfLikes.Count(),
                LikedBy = listOfLikes,
                NoReports = numberOfReports,
                Tags = tags,
                Lat = thread.Lat,
                Lng = thread.Lng
            };
            return View(model);
        }

        //only allow modertators and admins to access the page
        /*
         *      This is where you can change the number of reposts needed to be displayed on the report page
         */
        [Route("Reported")]
        [Authorize(Roles = "Admin, Mod")]
        public IActionResult Reported()
        {
            var threadModel = _service.GetAll().Select(threads => new ThreadModel
            {
                Id = threads.ID,
                Title = threads.Title,
                Created = threads.CreateDate,
                Description = threads.Description,
                Rating = threads.Votes,
                AuthorUserName = threads.UserName,
                NoReports = threads.NoReports
            })
                .Where(x => x.NoReports >= 1)
                .OrderByDescending(x => x.NoReports)
                .ToList();

            var threadList = new ThreadList { ThreadLists = threadModel };
            return View(threadList);
        }

        //Clears the reports that the thread had/has
        public async Task<IActionResult> ResetReports(int? threadsId)
        {
            await _service.ResetReports(threadsId);
            return RedirectToAction("Reported", "Thread");
        }

        //gives a user a warning and flaggs the thread/post
        public async Task<IActionResult> FlagPost(int? threadsId)
        {
            //flags a thread
            await _service.FlagThread(threadsId);
            return RedirectToAction("Reported", "Thread");
        }

        //Deletes the thread and gives a warning 
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AdminDelete(int? threadsId)
        {
            Thread t = _service.GetById(threadsId);
            var user = t.UserID;
            //delete from reports first
            await ResetReports(threadsId);
            //deletes the thread
            await _service.Delete(threadsId);
            //Gives a user a warining
            await _userService.GiveUserWarning(user);

            return RedirectToAction("Reported", "Thread");
        }

        /*
         *  Adding AI HERE 
         */

        /*
         * AUTHENTICATE
         * Creates a Computer Vision client used by each example.
         */
        private static ComputerVisionClient Authenticate(string endpoint, string key)
        {
            ComputerVisionClient client =
              new ComputerVisionClient(new ApiKeyServiceClientCredentials(key))
              { Endpoint = endpoint };
            return client;
        }

        private async Task<bool> AI(int? id)
        {
            var thread = _service.GetById(id);

            string imageUri = thread.Image;

            // Create a client
            ComputerVisionClient client = Authenticate(endpoint, subscriptionKey);

            var r = await _visionService.AnalyzeImageUrl(client, imageUri);

            return _visionService.Description(r);
        }

        //allows a user to report a thread
        [Authorize]
        public async Task<IActionResult> Report(int? threadId)
        {
            var username = _userManager.GetUserName(User);
            bool hasHumanParts = await AI(threadId);
            //add AI HERE for AI (need to call flag post if the AI description has a tag of any human parts)
            if (hasHumanParts)
            {
                await FlagPost(threadId);
            }
            await _service.Report(threadId, username);
            return RedirectToAction("Index", "Thread", new { @id = threadId });
        }

        [Route("Score/Threads")]
        public IActionResult Scores()
        {
            var threadModel = _service.GetAll().Select(threads => new ThreadModel
            {
                Title = threads.Title,
                Rating = threads.Votes,
                Created = threads.CreateDate,
                Picture = threads.Image,
                Id = threads.ID,
                Flagged = threads.Flagged,
                AlbumId = threads.AlbumId
            })
                .OrderByDescending(x => x.Rating)
                .ToList();

            var threadList = new ThreadList { ThreadLists = threadModel };
            return View(threadList);
        }

        //takes in a ajax call from the view, returns a JSON back to the view, the like btn
        [Authorize]
        public async Task<JsonResult> RatingIncrement([FromBody] int? id)
        {
            var userId = _userManager.GetUserId(User);  //gets the usersId
            if (id == null) return Json("Error");
            var wholeThread = _service.GetById(id);
            //make a list of users that liked the thread
            var listOfLikes = _service.ListOfLikes(id);
            //check if the user already pressed the btn
            if (_service.CheckAreadyLiked(wholeThread, userId) == true)
            {
                return Json(listOfLikes.Count());
            }
            else
            {
                //add the user that pressed the button to the list of liked on the thread
                await _service.AddUserToLikeList(id, userId);
                wholeThread.Votes = listOfLikes.Count();
                return Json(listOfLikes.Count());    //makes a json with the amount of votes that are currently in the database
            }

        }

        [Authorize]
        public async Task<JsonResult> RatingDecrease([FromBody] int? id)
        {
            var userId = _userManager.GetUserId(User);  //gets the usersId
            var wholeThread = _service.GetById(id);
            var listOfLikes = _service.ListOfLikes(id);
            if (id == null) NotFound();
            if (_service.CheckAreadyLiked(wholeThread, userId) == true)
            {
                //remove the user from the table
                await _service.RemoveUserFromLikeList(id, userId);
                //show the decerase 
                return Json(listOfLikes.Count());
            }
            else
            {
                return Json(listOfLikes.Count());    //makes a json with the amount of votes that are currently in the database
            }
        }

        // Visual to the website
        [Authorize]
        public IActionResult Create(int albumId)
        {
            if (albumId != 1)
            {
                var album = _albumService.GetAlbum(albumId);
                if (album == null) return NotFound();
                var channel = _channelService.GetChannel(album.ChannelId).Result;
                var user = _userManager.GetUserAsync(User).Result;
                var channelMember = _channelService.GetChannelMember(user, channel).Result;
                if (channelMember == null) return NotFound();

Login/Controllers/VisionController.cs
using Login.Data;
using Login.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision;
using System.Threading.Tasks;

namespace Login.Controllers
{
    [ApiController]
    [Authorize(Roles = "Admin")]
    public class VisionController : Controller
    {
        //azure vision api key and endpoint
        static string subscriptionKey = "5d7d56109a794e2b9532bdde2185755d";
        static string endpoint = "https://camaioai.cognitiveservices.azure.com/";
        //injections
        private readonly IThread _threadService;
        private readonly IVision _service;

        public VisionController(IVision service, IThread threadService)
        {
            _service = service;
            _threadService = threadService;
        }
        /*
         * AUTHENTICATE
         * Creates a Computer Vision client used by each example.
         */
        private static ComputerVisionClient Authenticate(string endpoint, string key)
        {
            ComputerVisionClient client =
              new ComputerVisionClient(new ApiKeyServiceClientCredentials(key))
              { Endpoint = endpoint };
            return client;
        }

        [Route("AI/{id}")]
        //[HttpGet("{id}")]
        public async Task<IActionResult> AI(int? id)
        {
            var thread = _threadService.GetById(id);

            if (thread == null)
            {
                return BadRequest();
            }
            string imageUri = thread.Image;

            // Create a client
            ComputerVisionClient client = Authenticate(endpoint, subscriptionKey);

            var r = await _service.AnalyzeImageUrl(client, imageUri);

            _service.Faces(r);
            _service.Objects(r);
            _service.Tags(r);

            var boolHuman = _service.Description(r);

            //return RedirectToAction("Index", "Thread", new { @id = thread.ID });
            return Json(boolHuman);
        }

        [Route("AIFULL/{id}")]
        [HttpGet]
        public async Task<IActionResult> FullAPI(int? id)
        {
            var thread = _threadService.GetById(id);
            if (thread == null)
            {
                return BadRequest();
            }
            string imageUri = thread.Image;

            // Create a client
            ComputerVisionClient client = Authenticate(endpoint, subscriptionKey);

            var r = await _service.AnalyzeImageUrl(client, imageUri);

            _service.Faces(r);
            _service.Objects(r);
            _service.Tags(r);

            return Json(r);
        }
    }
}

Login/Views/Thread/Create.cshtml
@model Login.Models.Threadl.ThreadModel

@{ 
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<div class="auth-form">
    <div class="content">
        <section>
            <form asp-action="AddThread" asp-route-albumId=@ViewData["albumId"] enctype="multipart/form-data" method="post">
                <div class="content">
                    <h1>@ViewData["Title"]</h1>
                </div>
                <div class="content">
                    <div class="form-group">
                        <label>Title: </label>
                        <span asp-validation-for="Title"></span>
                        <input asp-for="Title" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Description: </label>
                        <span asp-validation-for="Description"></span>
                        <input asp-for="Description" class="form-control" maxlength="256" />
                    </div>
                    <div class="form-group">
                        <label>Threads tags:</label>
                        <!--<label class="control-label"></label> -->
                        <input type="tags" name="tags" placeholder="Separate with commas" maxlength="64" class="form-control" />
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Picture">Picture: </label>
                        <span asp-validation-for="Picture"></span>
                        <input asp-for="Picture" type="file" id="file" name="file" />
                    </div>
                    <br />
                    <button type="submit" id="btn-light submitThreadBtn" class="createButton">
                        Submit
                    </button>
                    <input asp-for="AuthorId" type="hidden">
                    <input asp-for="Created" type="hidden">
                    <input asp-for="AuthorUserName" type="hidden">


                </div>
            </form>
        </section>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Login/Views/Thread/Delete.cshtml
@model Login.Models.Thread

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="auth-form p-2 d-flex flex-column justify-content-center">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div class="">
        <h4 class="form-group">Thread</h4>
        <hr />
        <dl class="row">
            <dt class="col-6">
                @Html.DisplayNameFor(model => model.UserName)
            </dt>
            <dd class="col-6">
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt class="col-6">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-6">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-6">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-6">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-6">
                @Html.DisplayNameFor(model => model.Votes)
            </dt>
            <dd class="col-6">
                @Html.DisplayFor(model => model.Votes)
            </dd>
        </dl>

        <form class="ml-auto" asp-action="DeleteThread" asp-route-id="@Model.ID">
            <input type="hidden" asp-for="ID" />
            <input type="submit" value="Delete" class="btn-danger rounded p-2" />
        </form>
        <a class="btn" asp-action="Index" asp-controller="Thread" asp-route-id="@Model.ID">Back</a>
    </div>
</div>

Login/Views/Thread/Edit.cshtml
@model Login.Models.Thread

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="auth-form p-2 d-flex flex-column">
    <div class="content">
        <h1>@ViewData["Title"] Thread</h1> 
    </div>
    

    </a>
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <input type="hidden" asp-for="UserID" />
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control w-100" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control w-100" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div>
            <label class="control-label">Thread tags</label>
            <input type="tags" name="tags" placeholder="Separate tags with comas" value=@ViewData["Tags"]>
        </div>
        <img src="@Model.Image" class="w-100 h-auto" />
        <input asp-for="Image" type="hidden">
        <input asp-for="CreateDate" type="hidden">
        <input asp-for="Votes" type="hidden">
        <input asp-for="UserName" type="hidden">
        <input asp-for="AlbumId" type="hidden">
        <input asp-for="Lat" type="hidden">
        <input asp-for="Lng" type="hidden">
        <div class="form-group my-3">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
        <a class="btn" asp-action="Index" asp-controller="Thread" asp-route-id="@Model.ID">Back</a>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Login/Views/Thread/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Login.Areas.Identity.Data
@model Login.Models.Threadl.ThreadModel
@inject UserManager<LoginUser> UserManager
@*this is the model that can be used within the View, check the path what can be passed in*@
@{
    ViewData["Title"] = "Thread Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header"></div>

<div class="top-score-card-display">
    <div class="row">
        <div id="DIV_3">
            <img class="card-img-top" src="@Model.Picture" alt="Card image cap" style="with: 700px; heght:500px">
        </div>
        <div id="DIV_4"></div>
        <div id="DIV_0">
            <div class="card-title"><h3>@Model.Title</h3></div>
            <div id="DIV_1"> 
                @foreach (var tag in Model.Tags)
                {   <tr>
                        <th>#@tag.Name</th>
                        <th></th>
                    </tr>
                }
                <div class="card-description"> 
                    <p class="card-text">@Model.Description </p> 
                </div>
                <div class="likes pt-2">
                    Likes: <h5 class="card-titl mt-1" id="like">@Model.Rating</h5>
                </div>
            </div>

            <div id="DIV_5">
                <div class="buttons">
                    @* Checks if a user is signed in and not viewing it as a guest *@
                    @if (User.Identity.Name != null)
                    {
                        <div id="likeSection">
                            @{
                                bool isLiked = false;
                                @foreach (var person in @Model.LikedBy)
                                {
                                    if (person.UserId == @UserManager.GetUserId(User))
                                    {
                                        isLiked = true;
                                        break;
                                    }
                                }
                                if (isLiked)
                                {
                                    <button type="button" id="likeBtn" class="createButton d-none" onclick="toggleLikeButton()">Like</button>
                                    <button type="button" id="disLikeBtn" class="createButton" onclick="toggleLikeButton()">Undo like</button>
                                }
                                else
                                {
                                    <button type="button" id="disLikeBtn" class="createButton d-none" onclick="toggleLikeButton()">Undo like</button>
                                    <button type="button" id="likeBtn" class="createButton" onclick="toggleLikeButton()">Like</button>
                                }
                            }
                        </div>
                    }
                </div>
            </div>

            <div id="DIV_2">
                <p></p>
                <a asp-action="Index" asp-controller="Profile" asp-route-username="@Model.AuthorUserName">
                    <h5 class="card-subtitle mb-2 text-muted">By: @Model.AuthorUserName</h5>
                    <h5 class="card-subtitle mb-2 text-muted">Created On: @Model.Created</h5>
                </a>
                @if (Model.Lng != null || Model.Lat != null)
                {
                    <a asp-action="Index" asp-controller="Map" asp-route-threadId="@Model.Id">
                        <h6 class="card-subtitle mb-2 text-muted">Location</h6>
                    </a>
                }
            </div>
        </div>
    </div>

    <br>
    <div class="card-footer">
        <small class="text-muted">
            <a asp-action="Report" asp-route-threadId="@Model.Id">Report </a>
            @if (User.Identity.Name == Model.AuthorUserName || User.IsInRole("Admin"))
            {
                <a asp-action="Edit" asp-route-threadId="@Model.Id">Edit </a>
                <a asp-action="Delete" asp-route-threadId="@Model.Id">Delete</a>
            }
            @if (User.IsInRole("Admin"))
            {
                <a asp-action="FullAPI" asp-controller="Vision" asp-route-id="@Model.Id"> | AI</a>
                <a asp-action="AI" asp-controller="Vision" asp-route-id="@Model.Id">AIHuman |</a>
            }
        </small>
    </div>

</div>

@section Scripts
{

    <script type="text/javascript">
        $(document).ready (function () {

            @*like btn here*@
            $('#likeBtn').click(function () {
                $.ajax({
                    type: "POST",
                    url: "/Thread/RatingIncrement",
                    dataType: 'JSON',
                    data: JSON.stringify(@Model.Id), @*Passes the current Id of the thread*@
                    contentType: "application/json",
                    success: function (result) {    @*If the response from the contoler is correct then do the following*@
                        $('#like').html(result);
                        console.log(result);
                    },
                    error: function (err) {
                        console.log("Error: " + err);
                    }
                })
            });

            @*unlike btn here*@
            $('#disLikeBtn').click(function () {
                $.ajax({
                    type: "POST",
                    url: "/Thread/RatingDecrease",
                    dataType: 'JSON',
                    data: JSON.stringify(@Model.Id), @*Passes the current Id of the thread*@
                    contentType: "application/json",
                    success: function (result) {    @*If the response from the contoler is correct then do the following*@
                        $('#like').html(result);
                        console.log(result);
                    },
                    error: function (err) {
                        console.log("Error: " + err);
                    }
                })
            });
        });
    </script>
}

Login/Views/Thread/Reported.cshtml
@model Login.Models.Threadl.ThreadList
@{
    ViewData["Title"] = "Report Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align:center; margin-top:2%">Reported Posts</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Number Of Reports</th>
            <th scope="col">Posted By</th>
            <th scope="col">Created On</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Rating</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var threads in Model.ThreadLists)
        {
        <tr>
            <td>
                @threads.NoReports
            </td>
            <td>
                <a asp-action="Index" asp-controller="Profile" asp-route-username="@threads.AuthorUserName">
                    @threads.AuthorUserName
                </a>
            </td>
            <td>@threads.Created</td>
            <td>
                <a asp-action="Index" asp-controller="Thread" asp-route-id="@threads.Id">
                    @threads.Title
                </a>
            </td>
            <td>@threads.Description</td>
            <td>@threads.Rating</td>
            <td>
                <a asp-action="AdminDelete" asp-controller="Thread" asp-route-threadsId="@threads.Id">Delete </a>|
                <a asp-action="FlagPost" asp-controller="Thread" asp-route-threadsId="@threads.Id"> Flag </a>|
                <a asp-action="ResetReports" asp-controller="Thread" asp-route-threadsId="@threads.Id"> Reset</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Login/Views/Thread/Scores.cshtml
@model Login.Models.Threadl.ThreadList
@{
    ViewData["Title"] = "Score Page";
    Layout = "~/Views/Shared/_Layout.cshtml";  
}
<h1 style="text-align:center; margin-top:2%">Top Posts</h1>   
<div class="top-score-row">  
    <br>
    @foreach (var threads in Model.ThreadLists){
        if (threads.Flagged == true || threads.AlbumId != 1)
        {
            continue;
        }
        <a asp-action="Index" asp-controller="Thread" asp-route-id="@threads.Id"> 
            <div class="top-score-column">
                <div class="top-score-card">
                    <h3>@threads.Title</h3>
                                <img class="top-posts-img" src="@threads.Picture" alt="Image" class="card-image"  style="width: 70%; height:275px;" />
                        <p>Rating: @threads.Rating</p>
                    <p>@threads.Created</p>
                </div>
                <br>
            </div>          
        </a>
    }
</div>

Login/Views/Thread/ThreadList.cshtml
@model Login.Models.Threadl.ThreadList
<h1>Threads</h1>
<a class="nav-link text-dark" asp-area="" asp-controller="Thread" asp-action="Create">Create New Thread</a>
<div class="card-deck">
    @foreach (var thread in Model.ThreadLists)
    {
         <div class="card">
            <img class="card-img-top" src="./download.svg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@thread.Title</h5>
                <p class="card-text">@thread.Description</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Uploaded 3 mins ago</small>
            </div>
        </div>
    }
</div>